#!/usr/bin/env perl
#Evaluate the alignment accuracy for data generated by ART

use strict ;
use warnings ;

die "usage: a.pl art.sam alignment.sam\n" if (@ARGV == 0) ;

my %truth ;
open FP, $ARGV[0] ;
while (<FP>)
{
	next if (/^@/) ;
	chomp ;
	my @cols = split ;
	$truth{$cols[0]} = $cols[2]."_".$cols[3] ; 
}
close FP ;

open FP, $ARGV[1] ;
my %match ;
my $matchCnt = 0 ;
my $readCnt = 0 ;
while (<FP>)
{
	next if (/^@/) ;
	chomp ;
	my @cols = split ;
	my $key = $cols[2]."_".$cols[3] ;
	if (!defined $match{$cols[0]})
	{
		$match{$cols[0]} = 0 ;
		++$readCnt ;
	}
	if ($truth{$cols[0]} eq $key)
	{
		++$matchCnt if ($match{$cols[0]} == 0);
		$match{$cols[0]} = 1 ;
	}
}
close FP ;

print "Accuracy=$matchCnt/$readCnt=".$matchCnt/$readCnt."\n" ;
if (0)
{
	foreach my $key (keys %match)
	{
		if ($match{$key} == 0)
		{
			print "$key\n" ;
		}
	}
}
